### ISSUE TITLE
Severe lack of ASCII Art

### ISSUE THREAD

**Issue by DLMousey** [Pilfer/iDictPy#1]
Your script doesn't even output ASCII art at random intervals, Do you even hacker bro?!

**Comment by Pilfer** [comment]
@DLMousey This would go against spec - see here: https://tools.ietf.org/html/rfc1945#section-2.1

**Comment by DLMousey** [comment]
A valid concern, however i'd argue that by the very nature of the project abuse of the protocol is an acceptable solution to the issue. Perhaps an alternative specification would be better suited to orient the project toward such as: https://tools.ietf.org/html/rfc2324
